---
- name: Create webroot
  file:
    state: directory
    path: /srv/www/
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Check if WordPress directory exists in /srv/www
  stat: path=/srv/www/{{server_hostname}}
  register: check_path

- name: Download WordPress
  get_url: 
    url: https://wordpress.org/wordpress-{{ wp_version }}.tar.gz 
    dest: /srv/www
  when: not check_path.stat.exists
- name: Extract WordPress
  unarchive:
    src: /srv/www/wordpress-{{ wp_version }}.tar.gz
    dest: /srv/www
    remote_src: yes
  when: not check_path.stat.exists
- name: Fetch random salts for WordPress config
  command: curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: Add wp-config
  template: "src=wp-config.php dest=/srv/www/wordpress/wp-config.php"
  become: yes

